In [1]:
from PIL import Image
import numpy as np

def array512(n):
  array_2d=np.zeros((n,n),dtype=np.int64)
  return array_2d
def contertTo256(img):
  #a=mean(img[i][i],img[i][i+1],img[i+1][i],img[i+1][i+1])
  return null



# Load the image
image = Image.open('input/1.png').convert('L')
# Convert the image to a 2D array
img = np.array(image)
# Show the array
print(img)
print(img.shape)



FileNotFoundError: ignored

In [ ]:
import numpy as np

# Create a 2D array with all values equal to 0
array_2d = np.zeros((512, 512), dtype=np.int64)

# Print the array
print(array_2d)
print(array_2d.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(512, 512)
